---
title: "R Notebook"
output: html_notebook
---

```{r}
library(dplyr)
library(psych)
library(stargazer)
library(xtable)
library(Hmisc)
library(broom)
library(tidyverse)
library(haven)
library(estimatr)
library(plm)
```


```{r}
# Load the data
df <- read.csv('final_dataset_mine.csv')
df
```

```{r}
df_treatment <- df %>%
  group_by('CRSP.Ticker', 'Fiscal.Quarter') %>%
  arrange('CRSP.Ticker', 'Fiscal.Quarter') %>%
  mutate(Below_Avg_Eps = ifelse('EPS.Basic' < lag('EPS.Basic', default = first('EPS.Basic')), 1, 0))
df_treatment
```


```{r}
# Create a treatment variable
df_treatment <- df %>%
  group_by(CRSP.Ticker, Fiscal.Quarter) %>%
  mutate(Below_Avg_Eps = ifelse(mean(EPS.Diluted) < lag(mean(EPS.Diluted)), 1, 0)) %>%
  ungroup()

df_treatment

# Create a dummy variable reflecting an industry
industry_dummies <- model.matrix(~GICS.Sector - 1, data = df_treatment)
# Attach the dummy variables to the original dataframe
new_df <- cbind(df_treatment, industry_dummies)
new_df
new_df <- new_df %>%
  ungroup()
new_df

```




```{r}
# First, let's see how does the ordinary model perform
ordinary_model <- glm(CEO.Dismissal ~ Below_Avg_Eps + Net.Income + Operating.Income + X3.Month.Treasury.Yield + Adjusted.Close, data = new_df, family = binomial)
stargazer(ordinary_model)
df_treatment
```
```{r}
# Assuming your dataframe is named 'your_data'
time_lagged_df <- new_df %>%
  arrange(CRSP.Ticker, Fiscal.Quarter) %>%
  group_by(CRSP.Ticker) %>%
  mutate(Below_Avg_Eps_Lagged = lag(ifelse(EPS.Basic
 < mean(EPS.Basic
), 1, 0)),
         Net_Income_Lagged = lag(Net.Income),
         Adjusted_Close_Price_Lagged = lag(Adjusted.Close),
         EPS_Lagged = lag(EPS.Basic),
         Operating_Income_Lagged = lag(Operating.Income))

# Drop the first row within each group (NaNs introduced by lag)
time_lagged_df <- time_lagged_df %>% filter(!is.na(Below_Avg_Eps_Lagged))

# Logistic regression model
forward_model <- glm(CEO.Dismissal ~ Below_Avg_Eps_Lagged + Net_Income_Lagged + 
                     Adjusted_Close_Price_Lagged + Operating_Income_Lagged + X3.Month.Treasury.Yield + Recession, 
                   data = time_lagged_df, 
                   family = binomial)

stargazer(forward_model)
logit_model_with_industry <- glm(CEO.Dismissal ~ Below_Avg_Eps_Lagged + Net_Income_Lagged + 
                     Adjusted_Close_Price_Lagged + Operating_Income_Lagged + X3.Month.Treasury.Yield + Recession +  `GICS.SectorInformation Technology` + `GICS.SectorIndustrials` + `GICS.SectorHealth Care` + `GICS.SectorFinancials` + `GICS.SectorEnergy` + `GICS.SectorMaterials` + `GICS.SectorUtilities` + `GICS.SectorConsumer Discretionary` + `GICS.SectorConsumer Staples` + `GICS.SectorCommunication Services`, 
                   data = time_lagged_df, 
                   family = binomial) 
```

